import type { Metadata } from 'next'
import { Open_Sans, Public_Sans, Playfair_Display } from 'next/font/google'
import './globals.css'

// const openSans = Open_Sans({
//   subsets: ['latin'],
//   display: 'swap',
//   //👇 Add variable to our object
//   variable: '--font-opensans',
// })

const publicSans = Public_Sans({
  subsets: ['latin'],
  display: 'swap',
})

// //👇 Configure the object for our second font
// const playfair = Playfair_Display({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-playfair',
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={publicSans.className}>{children}</body>
    </html>
  )
}
